#!/usr/bin/env python

# Simple cryptocurrency status blocklet for i3blocks using rate.sx API

# Copyright 2021 Estevão Santana
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import subprocess, re
from os import environ as env

# Set veriables from the os environment 
coin, currency, period = env.get('COIN'), env.get('CURRENCY'), env.get('PERIOD') 
#coin, currency, period = 'xmr', 'brl', '24h'

# Get the information from the API
cmd = "curl -s -f '{}.rate.sx/{}@{}' | sed -n '/begin/p;/avg/p'".format(currency, coin, period)   
data = subprocess.check_output(cmd,shell=True)

# Regex pattern to strip the unnecessary junk
pattern_strip = r'(\\x1b\[[0-9]*m)|(\\n)|(\/)|(\\.{3})'
patterns = [        
        r'(?<=end:\s)\$?\d*\.?\d*',
        r'[\+|\-]\d*\.\d*',
        r'[\+|\-]\d*\.\d*\%'
]

vls = list()
data_strip = re.sub(pattern_strip,'',str(data))

for px in patterns:
    vls.append(re.search(px,data_strip).group())

signal = re.search(r'^[\+|\-]',vls[1]).group()

color = {'-':'#FF0000','+':'#00FF00'}
span = "<span color='{}'>{}</span>"

cabs = span.format(color[signal],vls[1])
cperc = span.format(color[signal],vls[2])

display = '{}: {}  {}  {}  {}  {}'.format(
    coin.upper(),
    vls[0], 
    currency.upper(), 
    cabs, 
    cperc, 
    period
    ) 
 
print(display)
